/**
 * SAST — 소스 파일 정적 보안 분석.
 * 소스코드 파일을 업로드하면 위험 패턴(SQL 주입·XSS·평문 암호·취약 함수·
 * 하드코딩 자격증명·안전하지 않은 난수·경로 조작 등)을 탐지한다.
 * Semgrep 같은 외부 바이너리 없이 Node 표준으로 구현.
 */
import { id } from '../../util.js';
import type { Finding } from '../../types.js';

export interface SastRule {
  id: string;
  title: string;
  severity: Finding['severity'];
  cwe: string;
  owasp: string;
  pattern: RegExp;
  remediation: string;
  lang?: string[];   // 해당 언어(없으면 전체)
  confidence?: Finding['confidence'];  // 휴리스틱이면 'tentative'
  references?: string[];               // 참고 링크
}

export const SAST_RULES: SastRule[] = [
  // ── SQL 인젝션 ──────────────────────────────────────────────────
  { id: 'S001', title: 'SQL 쿼리 문자열 직접 연결(SQLi 위험)', severity: 'critical',
    cwe: 'CWE-89', owasp: 'A03:2021',
    pattern: /(?:query|execute|exec)\s*\(\s*(?:`|['"])[^'"`;]*\$\{|(?:query|execute|exec)\s*\(\s*[^)]*\+\s*(?:req\.|request\.|params\.|body\.)/i,
    remediation: '파라미터화 쿼리(Prepared Statement) 또는 ORM 을 사용하십시오.', lang: ['js','ts','py','php','java'] },
  { id: 'S002', title: 'Raw SQL with string format (SQLi)', severity: 'critical',
    cwe: 'CWE-89', owasp: 'A03:2021',
    pattern: /f['"]{1}.*SELECT.*\{|%s.*SELECT|\.format\(.*SELECT|sprintf.*SELECT/i,
    remediation: '파라미터화 쿼리를 사용하십시오.', lang: ['py','php'] },

  // ── XSS ─────────────────────────────────────────────────────────
  { id: 'S003', title: 'innerHTML 직접 할당(DOM XSS)', severity: 'high',
    cwe: 'CWE-79', owasp: 'A03:2021',
    pattern: /\.innerHTML\s*=\s*(?!['"`]<(?:span|div)[^>]*>[^<]*<\/(?:span|div)>['"`])[^;{]+/,
    remediation: 'textContent 를 사용하거나 DOMPurify 로 sanitize 하십시오.', lang: ['js','ts'] },
  { id: 'S004', title: 'eval() 사용(코드 인젝션)', severity: 'high',
    cwe: 'CWE-95', owasp: 'A03:2021',
    pattern: /\beval\s*\((?!['"`][^'"`,;)]+['"`]\))/,
    remediation: 'eval 사용을 제거하고 JSON.parse 또는 명시적 로직으로 대체하십시오.', lang: ['js','ts','py'] },
  { id: 'S005', title: 'document.write() 사용', severity: 'medium',
    cwe: 'CWE-79', owasp: 'A03:2021',
    pattern: /document\.write\s*\(/,
    remediation: 'document.write 대신 DOM API 를 사용하십시오.', lang: ['js','ts'] },

  // ── 하드코딩 자격증명 ────────────────────────────────────────────
  { id: 'S006', title: '하드코딩 패스워드/시크릿 (소스)', severity: 'high',
    cwe: 'CWE-798', owasp: 'A02:2021',
    pattern: /(?:password|passwd|secret|api_key|apikey|api_secret|access_key|private_key|token)\s*[=:]\s*['"](?![^'"]*(?:changeme|change[_-]?this|placeholder|your[_-]|my[_-]?secret|my[_-]?password|example|sample|dummy|redacted|insert[_-]|here|todo|fixme|xxx|<[^>]+>|\$\{|\.{3,}|\*{3,}))[^'"\s]{8,}['"]/i,
    remediation: '비밀정보를 환경변수 또는 시크릿 매니저로 이전하십시오. (자리표시자/예시 값은 제외됨)',
    confidence: 'tentative' },

  // ── 안전하지 않은 난수 ───────────────────────────────────────────
  { id: 'S007', title: 'Math.random() 보안 컨텍스트 사용', severity: 'medium',
    cwe: 'CWE-338', owasp: 'A02:2021',
    pattern: /Math\.random\(\).*(?:token|secret|key|password|session|nonce|csrf)/i,
    remediation: 'crypto.randomBytes() 또는 crypto.getRandomValues() 를 사용하십시오.', lang: ['js','ts'] },
  { id: 'S008', title: 'random.random() 보안 컨텍스트 사용', severity: 'medium',
    cwe: 'CWE-338', owasp: 'A02:2021',
    pattern: /random\.random\(\).*(?:token|secret|key|password|session)/i,
    remediation: 'secrets.token_hex() 를 사용하십시오.', lang: ['py'] },

  // ── 경로 조작 ────────────────────────────────────────────────────
  { id: 'S009', title: '경로 조작 가능성 (Path Traversal)', severity: 'high',
    cwe: 'CWE-22', owasp: 'A01:2021',
    pattern: /(?:readFile|readFileSync|createReadStream|open)\s*\(\s*(?:req\.|request\.|params\.|body\.|query\.)/i,
    remediation: 'path.basename() 으로 정규화하고 허용 디렉터리 밖 접근을 차단하십시오.', lang: ['js','ts'] },

  // ── 안전하지 않은 역직렬화 ──────────────────────────────────────
  { id: 'S010', title: 'pickle.loads() 역직렬화 — RCE 위험', severity: 'critical',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /pickle\.loads?\s*\(/,
    remediation: 'pickle 대신 json.loads() 를 사용하거나 신뢰하지 않는 데이터에 적용을 금지하십시오.', lang: ['py'] },
  { id: 'S011', title: 'unserialize() 역직렬화 — RCE 위험', severity: 'critical',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /unserialize\s*\(\s*(?:\$_(?:GET|POST|REQUEST|COOKIE)|user|input)/i,
    remediation: 'unserialize 에 사용자 입력을 허용하지 마십시오.', lang: ['php'] },
  { id: 'S012', title: 'ObjectInputStream 역직렬화 — RCE 위험', severity: 'critical',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /new\s+ObjectInputStream/,
    remediation: '신뢰하지 않는 스트림에 ObjectInputStream 사용을 금지하십시오.', lang: ['java'] },

  // ── SSRF ────────────────────────────────────────────────────────
  { id: 'S013', title: 'SSRF — 외부 URL 사용자 입력 직접 사용', severity: 'high',
    cwe: 'CWE-918', owasp: 'A10:2021',
    pattern: /fetch\s*\(\s*(?:req\.|request\.|params\.|body\.|query\.)|\$_(?:GET|POST|REQUEST)\[['"]url|urllib.*open\s*\(\s*(?:request\.|req\.)/i,
    remediation: 'URL 을 화이트리스트로 검증하고 내부 대역 접근을 차단하십시오.' },

  // ── 명령 인젝션 ──────────────────────────────────────────────────
  { id: 'S014', title: '쉘 명령 인젝션 위험', severity: 'critical',
    cwe: 'CWE-78', owasp: 'A03:2021',
    pattern: /(?:exec|execSync|spawn|system|popen|os\.system|subprocess\.call)\s*\([^)]*(?:\$\{|req\.|request\.|params\.|body\.)/i,
    remediation: 'execFile 과 인자 배열을 사용하고 사용자 입력을 shell 에 직접 전달하지 마십시오.' },

  // ── 암호화 약점 ──────────────────────────────────────────────────
  { id: 'S015', title: 'MD5/SHA1 패스워드 해시 사용', severity: 'high',
    cwe: 'CWE-327', owasp: 'A02:2021',
    pattern: /(?:md5|sha1)\s*\(\s*\$?password|hashlib\.(?:md5|sha1)\(\s*password/i,
    remediation: 'bcrypt, argon2, scrypt 같은 패스워드 해시 함수를 사용하십시오.' },
  { id: 'S016', title: 'ECB 모드 암호화 사용', severity: 'high',
    cwe: 'CWE-327', owasp: 'A02:2021',
    pattern: /(?:AES|DES)\/ECB|Cipher\.getInstance\s*\(\s*['"]AES\/ECB|createCipheriv\s*\(\s*['"]aes-\d+-ecb/i,
    remediation: 'GCM 또는 CBC 모드를 사용하십시오.', lang: ['java','js','ts'] },

  // ── 인증·세션 ────────────────────────────────────────────────────
  { id: 'S017', title: 'JWT 검증 알고리즘 미고정', severity: 'high',
    cwe: 'CWE-347', owasp: 'A02:2021',
    pattern: /jwt\.verify\s*\([^,]+,[^,]+\)(?!\s*,\s*\{[^}]*algorithms)/,
    remediation: 'algorithms 옵션으로 허용 알고리즘을 명시적으로 지정하십시오.', lang: ['js','ts'] },
  { id: 'S018', title: 'DEBUG=True 운영 노출 위험', severity: 'medium',
    cwe: 'CWE-489', owasp: 'A05:2021',
    pattern: /DEBUG\s*=\s*True/,
    remediation: '운영 환경에서 DEBUG=False 로 설정하십시오.', lang: ['py'] },

  // ── 보안 설정 ────────────────────────────────────────────────────
  { id: 'S019', title: 'SSL 인증서 검증 비활성화', severity: 'high',
    cwe: 'CWE-295', owasp: 'A02:2021',
    pattern: /verify\s*=\s*False|rejectUnauthorized\s*:\s*false|ssl\._create_unverified_context/i,
    remediation: 'SSL 인증서 검증을 활성화하십시오.' },
  { id: 'S020', title: 'CORS AllowAll origin 설정', severity: 'medium',
    cwe: 'CWE-942', owasp: 'A05:2021',
    pattern: /cors\s*\(\s*\{[^}]*origin\s*:\s*['"]\*['"]/i,
    remediation: '허용 출처를 구체적으로 지정하십시오.', lang: ['js','ts'] },
  { id: 'S021', title: 'CSRF 보호 비활성화', severity: 'high',
    cwe: 'CWE-352', owasp: 'A01:2021',
    pattern: /csrf_exempt|@csrf_protect\s*$|csrfProtection\s*=\s*false/i,
    remediation: 'CSRF 보호를 활성화하십시오.' },

  // ── 정보 노출 ────────────────────────────────────────────────────
  { id: 'S022', title: 'console.log 민감 정보 출력 가능성', severity: 'low',
    cwe: 'CWE-532', owasp: 'A09:2021',
    pattern: /console\.(?:log|debug|info)\s*\([^)]*(?:password|token|secret|key|credential)/i,
    remediation: '민감 정보를 로그에 출력하지 마십시오.', lang: ['js','ts'] },
  { id: 'S023', title: 'Stack trace 직접 응답 전송', severity: 'medium',
    cwe: 'CWE-209', owasp: 'A05:2021',
    pattern: /res\.(?:send|json)\s*\([^)]*(?:err\.stack|error\.stack|e\.stack)/i,
    remediation: '운영 환경에서 스택트레이스를 응답에 포함하지 마십시오.', lang: ['js','ts'] },

  // ───── 확장 점검: 하드코딩 시크릿(클라우드/SaaS 토큰) ─────
  { id: 'S024', title: 'AWS Access Key ID 하드코딩', severity: 'critical',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\b(?:AKIA|ASIA|AGPA|AIDA|AROA|ANPA|ANVA)[0-9A-Z]{16}\b/,
    remediation: 'AWS 키를 즉시 폐기·교체하고 IAM 역할 또는 시크릿 매니저를 사용하십시오.',
    confidence: 'firm', references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html'] },
  { id: 'S025', title: 'AWS Secret Access Key 하드코딩', severity: 'critical',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /aws_?secret_?access_?key\s*[=:]\s*['"][A-Za-z0-9/+]{40}['"]/i,
    remediation: 'AWS 비밀 키를 폐기하고 환경변수/시크릿 매니저로 이전하십시오.',
    confidence: 'firm' },
  { id: 'S026', title: 'GCP 서비스 계정 private_key 하드코딩', severity: 'critical',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /"private_key"\s*:\s*"-----BEGIN (?:RSA |EC )?PRIVATE KEY-----/,
    remediation: 'GCP 서비스 계정 키를 폐기하고 워크로드 아이덴티티를 사용하십시오.',
    confidence: 'firm' },
  { id: 'S027', title: 'GCP API 키 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bAIza[0-9A-Za-z\-_]{35}\b/,
    remediation: 'GCP API 키에 제한을 설정하고 소스에서 제거하십시오.',
    confidence: 'firm' },
  { id: 'S028', title: 'Azure Storage 연결 문자열 하드코딩', severity: 'critical',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /DefaultEndpointsProtocol=https?;AccountName=[^;]+;AccountKey=[A-Za-z0-9/+=]{20,}/i,
    remediation: 'Azure 키를 회전하고 Managed Identity 또는 Key Vault 를 사용하십시오.',
    confidence: 'firm' },
  { id: 'S029', title: 'Azure AD client secret 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /(?:client_?secret|azure_?client_?secret)\s*[=:]\s*['"][A-Za-z0-9~._\-]{30,}['"]/i,
    remediation: 'Azure AD 클라이언트 시크릿을 회전하고 인증서 기반 인증을 검토하십시오.',
    confidence: 'tentative' },
  { id: 'S030', title: 'Slack 토큰 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bxox[baprs]-[0-9A-Za-z\-]{10,}\b/,
    remediation: 'Slack 토큰을 폐기·재발급하고 환경변수로 이전하십시오.',
    confidence: 'firm' },
  { id: 'S031', title: 'Slack 웹훅 URL 하드코딩', severity: 'medium',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /https:\/\/hooks\.slack\.com\/services\/T[0-9A-Z]+\/B[0-9A-Z]+\/[0-9A-Za-z]+/,
    remediation: 'Slack 웹훅 URL 을 회전하고 시크릿으로 관리하십시오.',
    confidence: 'firm' },
  { id: 'S032', title: 'Discord 봇 토큰 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\b[MNO][A-Za-z\d_-]{23,26}\.[A-Za-z\d_-]{6}\.[A-Za-z\d_-]{27,40}\b/,
    remediation: 'Discord 봇 토큰을 재발급하고 소스에서 제거하십시오.',
    confidence: 'tentative' },
  { id: 'S033', title: 'Discord 웹훅 URL 하드코딩', severity: 'medium',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /https:\/\/(?:ptb\.|canary\.)?discord(?:app)?\.com\/api\/webhooks\/\d+\/[\w-]+/,
    remediation: 'Discord 웹훅을 삭제·재생성하고 시크릿으로 관리하십시오.',
    confidence: 'firm' },
  { id: 'S034', title: 'Telegram 봇 토큰 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\b\d{8,10}:[A-Za-z0-9_-]{35}\b/,
    remediation: 'Telegram 봇 토큰을 @BotFather 로 재발급하십시오.',
    confidence: 'tentative' },
  { id: 'S035', title: 'GitHub 토큰(PAT/OAuth/App) 하드코딩', severity: 'critical',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\b(?:ghp|gho|ghu|ghs|ghr)_[0-9A-Za-z]{36}\b|\bgithub_pat_[0-9A-Za-z_]{50,}\b/,
    remediation: 'GitHub 토큰을 즉시 폐기하고 세분화된 권한으로 재발급하십시오.',
    confidence: 'firm' },
  { id: 'S036', title: 'Stripe 비밀 키 하드코딩', severity: 'critical',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\b(?:sk|rk)_(?:live|test)_[0-9A-Za-z]{24,}\b/,
    remediation: 'Stripe 키를 롤링(회전)하고 서버 측 환경변수로만 관리하십시오.',
    confidence: 'firm' },
  { id: 'S037', title: 'Twilio Account SID/Auth Token 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bAC[0-9a-fA-F]{32}\b|twilio_?auth_?token\s*[=:]\s*['"][0-9a-f]{32}['"]/i,
    remediation: 'Twilio Auth Token 을 회전하고 환경변수로 이전하십시오.',
    confidence: 'firm' },
  { id: 'S038', title: 'SendGrid API 키 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b/,
    remediation: 'SendGrid API 키를 폐기·재발급하십시오.',
    confidence: 'firm' },
  { id: 'S039', title: 'Mailgun API 키 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bkey-[0-9a-f]{32}\b|mailgun_?api_?key\s*[=:]\s*['"][0-9a-f]{32,}['"]/i,
    remediation: 'Mailgun 키를 회전하고 시크릿 매니저로 이전하십시오.',
    confidence: 'tentative' },
  { id: 'S040', title: 'npm 액세스 토큰 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bnpm_[0-9A-Za-z]{36}\b/,
    remediation: 'npm 토큰을 폐기하고 .npmrc 를 시크릿으로 관리하십시오.',
    confidence: 'firm' },
  { id: 'S041', title: 'PyPI 업로드 토큰 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bpypi-AgEIcHlwaS[A-Za-z0-9_-]{20,}\b/,
    remediation: 'PyPI API 토큰을 폐기·재발급하십시오.',
    confidence: 'firm' },
  { id: 'S042', title: 'Google OAuth client secret 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\bGOCSPX-[A-Za-z0-9_-]{28}\b/,
    remediation: 'OAuth 클라이언트 시크릿을 재발급하고 서버에서만 보관하십시오.',
    confidence: 'firm' },
  { id: 'S043', title: '.htpasswd 자격증명 하드코딩', severity: 'medium',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /^[A-Za-z0-9._-]+:\$(?:apr1|2[aby]|6)\$[^\s:]+$/m,
    remediation: 'htpasswd 파일을 소스 저장소에서 제거하고 접근을 제한하십시오.',
    confidence: 'tentative' },
  { id: 'S044', title: 'PEM Private Key 블록 하드코딩', severity: 'critical',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----/,
    remediation: '개인키를 즉시 폐기·재발급하고 소스에서 제거하십시오.',
    confidence: 'firm' },
  { id: 'S045', title: '하드코딩 JWT(eyJ...) 토큰', severity: 'medium',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/,
    remediation: '소스에 JWT 를 하드코딩하지 말고 런타임에 발급하십시오.',
    confidence: 'tentative' },
  { id: 'S046', title: 'DB 접속 문자열(자격증명 포함) 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis|amqp|mssql):\/\/[^:@\s'"]+:[^@\s'"]+@/i,
    remediation: '접속 문자열을 환경변수로 분리하고 자격증명을 회전하십시오.',
    confidence: 'firm' },

  // ───── 확장 점검: 위험 sink(코드 실행/역직렬화/템플릿) ─────
  { id: 'S047', title: 'Function 생성자 동적 코드 실행', severity: 'high',
    cwe: 'CWE-95', owasp: 'A03:2021',
    pattern: /\bnew\s+Function\s*\(|(?<![\w.])Function\s*\(\s*['"][^'"]*\breturn\b/,
    remediation: 'Function 생성자 대신 명시적 로직을 사용하십시오.', lang: ['js','ts'],
    confidence: 'firm' },
  { id: 'S048', title: 'setTimeout/setInterval 문자열 인자(암묵적 eval)', severity: 'medium',
    cwe: 'CWE-95', owasp: 'A03:2021',
    pattern: /set(?:Timeout|Interval)\s*\(\s*['"`]/,
    remediation: '콜백 함수를 전달하십시오(문자열 금지).', lang: ['js','ts'],
    confidence: 'firm' },
  { id: 'S049', title: 'child_process 사용(명령 실행 표면)', severity: 'medium',
    cwe: 'CWE-78', owasp: 'A03:2021',
    pattern: /require\(\s*['"]child_process['"]\s*\)|from\s+['"]node:child_process['"]/,
    remediation: 'execFile/spawn 에 인자 배열을 사용하고 입력을 검증하십시오.', lang: ['js','ts'],
    confidence: 'tentative' },
  { id: 'S050', title: 'subprocess shell=True 사용', severity: 'high',
    cwe: 'CWE-78', owasp: 'A03:2021',
    pattern: /subprocess\.(?:run|call|Popen|check_output|check_call)\s*\([^)]*shell\s*=\s*True/,
    remediation: 'shell=False 와 인자 리스트를 사용하십시오.', lang: ['py'],
    confidence: 'firm' },
  { id: 'S051', title: 'os.popen/commands.getoutput 사용', severity: 'medium',
    cwe: 'CWE-78', owasp: 'A03:2021',
    pattern: /\bos\.popen\s*\(|commands\.get(?:status)?output\s*\(/,
    remediation: 'subprocess 의 인자 리스트 형태를 사용하십시오.', lang: ['py'],
    confidence: 'tentative' },
  { id: 'S052', title: 'Java Runtime.exec / ProcessBuilder 사용', severity: 'medium',
    cwe: 'CWE-78', owasp: 'A03:2021',
    pattern: /Runtime\.getRuntime\(\)\.exec\s*\(|new\s+ProcessBuilder\s*\(/,
    remediation: '입력을 검증하고 인자를 배열로 분리하십시오.', lang: ['java'],
    confidence: 'tentative' },
  { id: 'S053', title: 'PHP 코드 실행 함수(eval/assert/create_function)', severity: 'high',
    cwe: 'CWE-95', owasp: 'A03:2021',
    pattern: /\b(?:eval|assert|create_function|call_user_func)\s*\(\s*\$(?:_(?:GET|POST|REQUEST|COOKIE)|[A-Za-z_]\w*)/,
    remediation: '동적 코드 실행을 제거하고 화이트리스트 기반 분기를 사용하십시오.', lang: ['php'],
    confidence: 'firm' },
  { id: 'S054', title: 'PHP 명령 실행 함수(system/exec/passthru/shell_exec)', severity: 'high',
    cwe: 'CWE-78', owasp: 'A03:2021',
    pattern: /\b(?:system|exec|passthru|shell_exec|proc_open|popen)\s*\(\s*[^)]*\$_(?:GET|POST|REQUEST|COOKIE)/,
    remediation: 'escapeshellarg/escapeshellcmd 으로 인자를 처리하거나 사용을 제거하십시오.', lang: ['php'],
    confidence: 'firm' },
  { id: 'S055', title: 'Ruby 명령 실행(백틱/system/%x/Kernel.exec)', severity: 'high',
    cwe: 'CWE-78', owasp: 'A03:2021',
    pattern: /(?:`[^`]*#\{|%x\([^)]*#\{|system\s*\(?\s*["'][^"']*#\{|Kernel\.(?:system|exec)\s*\()/,
    remediation: '인자를 배열로 분리한 system(["cmd", arg]) 형태를 사용하십시오.', lang: ['rb'],
    confidence: 'firm' },
  { id: 'S056', title: 'Ruby eval/instance_eval/send 동적 실행', severity: 'high',
    cwe: 'CWE-95', owasp: 'A03:2021',
    pattern: /\b(?:eval|instance_eval|class_eval|module_eval)\s*\(|\.send\s*\(\s*params\[/,
    remediation: '동적 평가/메서드 디스패치에 사용자 입력을 허용하지 마십시오.', lang: ['rb'],
    confidence: 'tentative' },
  { id: 'S057', title: 'yaml.load() SafeLoader 미지정(역직렬화)', severity: 'critical',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /yaml\.load\s*\((?![^)]*Safe(?:Loader)?)(?![^)]*Loader\s*=\s*yaml\.SafeLoader)/,
    remediation: 'yaml.safe_load() 또는 Loader=SafeLoader 를 사용하십시오.', lang: ['py'],
    confidence: 'firm' },
  { id: 'S058', title: 'Python marshal/shelve 역직렬화', severity: 'high',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /\bmarshal\.loads?\s*\(|\bshelve\.open\s*\(/,
    remediation: '신뢰하지 않는 데이터에 marshal/shelve 를 사용하지 마십시오.', lang: ['py'],
    confidence: 'tentative' },
  { id: 'S059', title: 'Ruby Marshal.load 역직렬화 — RCE 위험', severity: 'critical',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /Marshal\.load\s*\(/,
    remediation: '신뢰하지 않는 입력에 Marshal.load 를 사용하지 마십시오.', lang: ['rb'],
    confidence: 'firm' },
  { id: 'S060', title: 'Ruby YAML.load 역직렬화 — RCE 위험', severity: 'high',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /YAML\.load\s*\((?![^)]*safe)/,
    remediation: 'YAML.safe_load 를 사용하십시오.', lang: ['rb'],
    confidence: 'firm' },
  { id: 'S061', title: '.NET BinaryFormatter 역직렬화 — RCE 위험', severity: 'critical',
    cwe: 'CWE-502', owasp: 'A08:2021',
    pattern: /new\s+BinaryFormatter\s*\(|BinaryFormatter\s*\(\s*\)\.Deserialize/,
    remediation: 'BinaryFormatter 사용을 중단하고 System.Text.Json 등을 사용하십시오.', lang: ['cs'],
    confidence: 'firm' },
  { id: 'S062', title: 'Flask render_template_string 템플릿 인젝션(SSTI)', severity: 'high',
    cwe: 'CWE-94', owasp: 'A03:2021',
    pattern: /render_template_string\s*\([^)]*(?:request\.|\+|%|\.format\(|f['"])/,
    remediation: '사용자 입력을 템플릿 문자열에 직접 삽입하지 마십시오.', lang: ['py'],
    confidence: 'firm' },
  { id: 'S063', title: 'Handlebars.compile 동적 템플릿(SSTI)', severity: 'medium',
    cwe: 'CWE-94', owasp: 'A03:2021',
    pattern: /Handlebars\.compile\s*\(\s*(?:req\.|request\.|body\.|params\.|query\.)/,
    remediation: '템플릿 소스를 사용자 입력으로 컴파일하지 마십시오.', lang: ['js','ts'],
    confidence: 'firm' },

  // ───── 확장 점검: SQL/경로/SSRF 추가 ─────
  { id: 'S064', title: 'Python execute(f"...") SQL 포맷 구성(SQLi)', severity: 'critical',
    cwe: 'CWE-89', owasp: 'A03:2021',
    pattern: /\.execute(?:many)?\s*\(\s*f['"][^'"]*\{/,
    remediation: '파라미터 바인딩(%s, ?)을 사용하십시오.', lang: ['py'],
    confidence: 'firm' },
  { id: 'S065', title: 'SQL 문자열 연결(+ 변수 +) 구성(SQLi)', severity: 'high',
    cwe: 'CWE-89', owasp: 'A03:2021',
    pattern: /(?:SELECT|INSERT|UPDATE|DELETE)\b[^;'"]*['"]\s*\+\s*\w+\s*\+\s*['"]/i,
    remediation: '파라미터화 쿼리를 사용하십시오.',
    confidence: 'tentative' },
  { id: 'S066', title: 'Go fmt.Sprintf 로 SQL 구성(SQLi)', severity: 'high',
    cwe: 'CWE-89', owasp: 'A03:2021',
    pattern: /fmt\.Sprintf\s*\(\s*["'][^"']*(?:SELECT|INSERT|UPDATE|DELETE)[^"']*%[sv]/i,
    remediation: 'database/sql 의 플레이스홀더(?, $1)와 인자를 사용하십시오.', lang: ['go'],
    confidence: 'firm' },
  { id: 'S067', title: 'Go database/sql 문자열 연결 쿼리(SQLi)', severity: 'high',
    cwe: 'CWE-89', owasp: 'A03:2021',
    pattern: /db\.(?:Query|Exec|QueryRow)(?:Context)?\s*\(\s*["'][^"']*["']\s*\+/,
    remediation: '플레이스홀더와 인자 바인딩을 사용하십시오.', lang: ['go'],
    confidence: 'firm' },
  { id: 'S068', title: 'Java Statement 문자열 연결 쿼리(SQLi)', severity: 'high',
    cwe: 'CWE-89', owasp: 'A03:2021',
    pattern: /(?:createStatement\(\)|statement)\.execute(?:Query|Update)?\s*\(\s*["'][^"']*["']\s*\+|String\s+\w*[Qq]uery\s*=\s*["'][^"']*(?:SELECT|INSERT|UPDATE|DELETE)[^"']*["']\s*\+/,
    remediation: 'PreparedStatement 와 setXxx 바인딩을 사용하십시오.', lang: ['java'],
    confidence: 'tentative' },
  { id: 'S069', title: 'path.join 에 사용자 입력(경로 조작)', severity: 'high',
    cwe: 'CWE-22', owasp: 'A01:2021',
    pattern: /path\.(?:join|resolve)\s*\([^)]*(?:req\.|request\.|params\.|body\.|query\.)/,
    remediation: 'path.basename 후 허용 루트 기준 경로를 검증하십시오.', lang: ['js','ts'],
    confidence: 'firm' },
  { id: 'S070', title: 'Python open() 에 사용자 입력(경로 조작)', severity: 'high',
    cwe: 'CWE-22', owasp: 'A01:2021',
    pattern: /\bopen\s*\(\s*(?:request\.|os\.path\.join\s*\([^)]*request\.|flask\.request\.|f['"][^'"]*\{)/,
    remediation: 'os.path.basename 후 허용 디렉터리 안인지 검증하십시오.', lang: ['py'],
    confidence: 'tentative' },
  { id: 'S071', title: 'send_file/sendFile 에 사용자 입력', severity: 'high',
    cwe: 'CWE-22', owasp: 'A01:2021',
    pattern: /(?:send_file|sendFile)\s*\(\s*(?:req\.|request\.|params\.|body\.|query\.)/i,
    remediation: '허용 파일 목록 또는 안전한 경로 검증을 적용하십시오.',
    confidence: 'firm' },
  { id: 'S072', title: 'Python requests 에 사용자 URL(SSRF)', severity: 'high',
    cwe: 'CWE-918', owasp: 'A10:2021',
    pattern: /requests\.(?:get|post|put|head|request)\s*\(\s*(?:request\.|flask\.request\.|f['"][^'"]*\{|[a-z_]+_url\s*[,)])/,
    remediation: 'URL 화이트리스트 검증과 내부 대역 차단을 적용하십시오.', lang: ['py'],
    confidence: 'tentative' },
  { id: 'S073', title: 'urllib.urlopen 에 사용자 URL(SSRF)', severity: 'high',
    cwe: 'CWE-918', owasp: 'A10:2021',
    pattern: /urllib(?:\.request)?\.urlopen\s*\(\s*(?:request\.|flask\.request\.)/,
    remediation: 'URL 검증과 SSRF 가드를 적용하십시오.', lang: ['py'],
    confidence: 'firm' },
  { id: 'S074', title: 'Go http.Get 에 사용자 URL(SSRF)', severity: 'medium',
    cwe: 'CWE-918', owasp: 'A10:2021',
    pattern: /http\.(?:Get|Post|Head)\s*\(\s*(?:r\.FormValue|r\.URL\.Query|c\.Query|req\.)/,
    remediation: 'URL 화이트리스트와 내부 대역 차단을 적용하십시오.', lang: ['go'],
    confidence: 'tentative' },

  // ───── 확장 점검: 암호화 약점 추가 ─────
  { id: 'S075', title: 'DES/3DES/RC4/Blowfish 취약 알고리즘 사용', severity: 'high',
    cwe: 'CWE-327', owasp: 'A02:2021',
    pattern: /\b(?:DESede|TripleDES|3DES|RC4|ARCFOUR|Blowfish)\b|createcipher(?:iv)?\s*\(\s*['"](?:des|rc4|bf)/i,
    remediation: 'AES-GCM 등 현대 알고리즘으로 교체하십시오.',
    confidence: 'tentative' },
  { id: 'S076', title: '하드코딩 IV(초기화 벡터)', severity: 'medium',
    cwe: 'CWE-329', owasp: 'A02:2021',
    pattern: /\b(?:iv|initialization_?vector)\s*[=:]\s*(?:['"][0-9A-Fa-f]{16,}['"]|Buffer\.from\(\s*['"][0-9A-Fa-f]{16,}['"]|b['"][^'"]{8,}['"])/i,
    remediation: '암호화마다 무작위 IV 를 생성하십시오.',
    confidence: 'tentative' },
  { id: 'S077', title: '하드코딩 salt 값', severity: 'medium',
    cwe: 'CWE-760', owasp: 'A02:2021',
    pattern: /\bsalt\s*[=:]\s*['"][^'"]{6,}['"]/i,
    remediation: '사용자마다 무작위 salt 를 생성·저장하십시오.',
    confidence: 'tentative' },
  { id: 'S078', title: 'MD5/SHA1 일반 해시 사용', severity: 'medium',
    cwe: 'CWE-327', owasp: 'A02:2021',
    pattern: /\b(?:createHash\s*\(\s*['"](?:md5|sha1)['"]|hashlib\.(?:md5|sha1)\s*\((?!\s*\$?password\b)|MessageDigest\.getInstance\s*\(\s*["'](?:MD5|SHA-?1)["'])/i,
    remediation: '무결성/식별 외 보안 용도라면 SHA-256 이상을 사용하십시오.',
    confidence: 'tentative' },
  { id: 'S079', title: 'Go InsecureSkipVerify TLS 검증 비활성화', severity: 'high',
    cwe: 'CWE-295', owasp: 'A02:2021',
    pattern: /InsecureSkipVerify\s*:\s*true/,
    remediation: '인증서 검증을 활성화하십시오.', lang: ['go'],
    confidence: 'firm' },
  { id: 'S080', title: '.NET 인증서 검증 우회(ServerCertificateValidationCallback)', severity: 'high',
    cwe: 'CWE-295', owasp: 'A02:2021',
    pattern: /ServerCertificateValidationCallback\s*[+]?=\s*(?:\([^)]*\)\s*=>\s*true|delegate)/,
    remediation: '실제 인증서 검증 로직을 구현하십시오.', lang: ['cs'],
    confidence: 'firm' },
  { id: 'S081', title: '레거시 TLS(TLSv1/TLSv1.1) 강제 사용', severity: 'medium',
    cwe: 'CWE-326', owasp: 'A02:2021',
    pattern: /\bSSLv3\b|\bSSLv23\b|\bTLSv1(?:\.1)?(?![.\d])|\bPROTOCOL_TLSv1(?:_1)?(?!_?[23])\b|\bTLS1_VERSION\b|minVersion\s*:\s*['"]TLSv1(?:\.1)?['"](?!\d)/,
    remediation: 'TLS 1.2 이상만 허용하십시오.',
    confidence: 'tentative' },
  { id: 'S082', title: 'Java SecureRandom 대신 java.util.Random 사용', severity: 'medium',
    cwe: 'CWE-330', owasp: 'A02:2021',
    pattern: /new\s+Random\s*\(\s*\)[^;]*(?:token|secret|key|password|session|nonce|otp)/i,
    remediation: 'java.security.SecureRandom 을 사용하십시오.', lang: ['java'],
    confidence: 'tentative' },
  { id: 'S083', title: 'PHP 약한 난수(rand/mt_rand) 보안 컨텍스트', severity: 'medium',
    cwe: 'CWE-338', owasp: 'A02:2021',
    pattern: /\b(?:mt_rand|rand|uniqid)\s*\([^)]*\)[^;]*(?:token|secret|key|password|session|csrf)/i,
    remediation: 'random_bytes()/random_int() 를 사용하십시오.', lang: ['php'],
    confidence: 'tentative' },

  // ───── 확장 점검: XSS/프론트엔드 ─────
  { id: 'S084', title: 'React dangerouslySetInnerHTML 사용', severity: 'high',
    cwe: 'CWE-79', owasp: 'A03:2021',
    pattern: /dangerouslySetInnerHTML\s*=\s*\{\{/,
    remediation: '신뢰할 수 없는 HTML 은 DOMPurify 로 sanitize 하십시오.', lang: ['js','ts'],
    confidence: 'firm' },
  { id: 'S085', title: 'Vue v-html 디렉티브 사용(XSS)', severity: 'medium',
    cwe: 'CWE-79', owasp: 'A03:2021',
    pattern: /v-html\s*=\s*["']/,
    remediation: '신뢰할 수 없는 데이터에 v-html 을 쓰지 말고 sanitize 하십시오.', lang: ['js','ts'],
    confidence: 'tentative' },
  { id: 'S086', title: 'outerHTML/insertAdjacentHTML 직접 할당(DOM XSS)', severity: 'medium',
    cwe: 'CWE-79', owasp: 'A03:2021',
    pattern: /\.outerHTML\s*=|\.insertAdjacentHTML\s*\(/,
    remediation: 'textContent 또는 sanitize 된 값을 사용하십시오.', lang: ['js','ts'],
    confidence: 'tentative' },
  { id: 'S087', title: 'jQuery .html()/$() 동적 HTML(XSS)', severity: 'medium',
    cwe: 'CWE-79', owasp: 'A03:2021',
    pattern: /\$\([^)]*(?:location|req\.|params\.|query\.|window\.name)[^)]*\)\.html\s*\(|\.html\s*\(\s*(?:location|window\.location|document\.URL)/,
    remediation: '.text() 또는 sanitize 를 사용하십시오.', lang: ['js','ts'],
    confidence: 'tentative' },
  { id: 'S088', title: 'PHP echo 에 사용자 입력 직접 출력(XSS)', severity: 'high',
    cwe: 'CWE-79', owasp: 'A03:2021',
    pattern: /\b(?:echo|print)\s+[^;]*\$_(?:GET|POST|REQUEST|COOKIE)\[[^\]]+\]\s*;/,
    remediation: 'htmlspecialchars() 로 출력 인코딩하십시오.', lang: ['php'],
    confidence: 'firm' },
  { id: 'S089', title: 'location.href/assign 에 비신뢰 입력(오픈 리다이렉트)', severity: 'medium',
    cwe: 'CWE-601', owasp: 'A01:2021',
    pattern: /(?:location\.href|location\.assign|window\.location)\s*=\s*(?:req\.|params\.|query\.|getParameter|new\s+URLSearchParams)/,
    remediation: '리다이렉트 대상을 화이트리스트로 검증하십시오.', lang: ['js','ts'],
    confidence: 'tentative' },

  // ───── 확장 점검: 기타(설정/로직/로깅) ─────
  { id: 'S090', title: 'Go CORS 와일드카드 Origin 설정', severity: 'medium',
    cwe: 'CWE-942', owasp: 'A05:2021',
    pattern: /(?:Header\(\)\.Set|w\.Header\(\)\.Set)\s*\(\s*["']Access-Control-Allow-Origin["']\s*,\s*["']\*["']/,
    remediation: '허용 출처를 구체적으로 지정하십시오.', lang: ['go'],
    confidence: 'firm' },
  { id: 'S091', title: 'Access-Control-Allow-Credentials 와 와일드카드 Origin 동시 사용', severity: 'medium',
    cwe: 'CWE-942', owasp: 'A05:2021',
    pattern: /Access-Control-Allow-Origin["']?\s*[:,]\s*["']?\*["']?[^\n]*Access-Control-Allow-Credentials["']?\s*[:,]\s*["']?true|Access-Control-Allow-Credentials["']?\s*[:,]\s*["']?true[^\n]*Access-Control-Allow-Origin["']?\s*[:,]\s*["']?\*/i,
    remediation: 'credentials 허용 시 Origin 을 와일드카드(*)가 아닌 구체값으로 지정하십시오. 와일드카드 Origin 이 같은 줄에 없으면 정상 설정일 수 있습니다.',
    confidence: 'tentative' },
  { id: 'S092', title: '타이밍 비안전 토큰/시크릿 == 비교', severity: 'medium',
    cwe: 'CWE-208', owasp: 'A02:2021',
    pattern: /(?:token|secret|api_?key|hmac|signature|password)\s*===?\s*(?:req\.|request\.|params\.|body\.|query\.|user|input)/i,
    remediation: 'crypto.timingSafeEqual / hmac.compare_digest 같은 상수시간 비교를 사용하십시오.',
    confidence: 'tentative' },
  { id: 'S093', title: '하드코딩 비밀번호 비교', severity: 'high',
    cwe: 'CWE-798', owasp: 'A07:2021',
    pattern: /(?:password|passwd|pwd)\s*===?\s*['"][^'"]{3,}['"]/i,
    remediation: '비밀번호를 하드코딩 비교하지 말고 해시 검증을 사용하십시오.',
    confidence: 'firm' },
  { id: 'S094', title: '정규식 DoS(ReDoS) 위험 중첩 수량자', severity: 'medium',
    cwe: 'CWE-1333', owasp: 'A06:2021',
    pattern: /new\s+RegExp\s*\([^)]*(?:\(\.\*\)\+|\(\.\+\)\+|\(\[\^[^\]]*\]\+\)\+|\([^)]*\+\)\+)/,
    remediation: '중첩 수량자를 제거하거나 입력 길이를 제한하십시오.', lang: ['js','ts'],
    confidence: 'tentative' },
  { id: 'S095', title: 'Express 와일드카드 CORS 미들웨어(origin true)', severity: 'medium',
    cwe: 'CWE-942', owasp: 'A05:2021',
    pattern: /cors\s*\(\s*\{[^}]*origin\s*:\s*true[^}]*credentials\s*:\s*true/,
    remediation: 'credentials 사용 시 origin 을 구체적으로 지정하십시오.', lang: ['js','ts'],
    confidence: 'firm' },
  { id: 'S096', title: 'Flask app.run(debug=True) 운영 노출', severity: 'medium',
    cwe: 'CWE-489', owasp: 'A05:2021',
    pattern: /\.run\s*\([^)]*debug\s*=\s*True/,
    remediation: '운영 환경에서 debug 를 비활성화하십시오.', lang: ['py'],
    confidence: 'firm' },
  { id: 'S097', title: 'Django SECRET_KEY 하드코딩', severity: 'high',
    cwe: 'CWE-798', owasp: 'A05:2021',
    pattern: /SECRET_KEY\s*=\s*['"][^'"]{16,}['"]/,
    remediation: 'SECRET_KEY 를 환경변수로 분리하십시오.', lang: ['py'],
    confidence: 'firm' },
  { id: 'S098', title: 'Python logging 에 민감 정보 출력', severity: 'low',
    cwe: 'CWE-532', owasp: 'A09:2021',
    pattern: /(?:logging|logger|log)\.(?:info|debug|warning|error)\s*\([^)]*(?:password|token|secret|api_?key|credential)/i,
    remediation: '민감 정보를 로그에 남기지 마십시오.', lang: ['py'],
    confidence: 'tentative' },
  { id: 'S099', title: 'JWT alg:none / verify:false 허용', severity: 'high',
    cwe: 'CWE-347', owasp: 'A02:2021',
    pattern: /(?:algorithm[s]?\s*[:=]\s*['"]none['"]|verify_?signature\s*[:=]\s*[Ff]alse|jwt\.decode\s*\([^)]*verify\s*=\s*False)/,
    remediation: 'alg=none 을 거부하고 서명 검증을 항상 활성화하십시오.',
    confidence: 'firm' },
  { id: 'S100', title: 'Python assert 로 보안 검증(최적화시 무시됨)', severity: 'low',
    cwe: 'CWE-617', owasp: 'A04:2021',
    pattern: /\bassert\s+(?:request\.|user\.|is_authenticated|has_perm|current_user)/,
    remediation: 'assert 대신 명시적 조건 검사와 예외를 사용하십시오(-O 시 제거됨).', lang: ['py'],
    confidence: 'tentative' },
  { id: 'S101', title: 'XML 외부 엔티티 처리 활성화(XXE)', severity: 'high',
    cwe: 'CWE-611', owasp: 'A05:2021',
    pattern: /(?:resolve_entities\s*=\s*True|XMLParser\s*\([^)]*resolve_entities\s*=\s*True|setFeature\s*\(\s*["'][^"']*external-general-entities["']\s*,\s*true|noent\s*=\s*True)/,
    remediation: '외부 엔티티 처리를 비활성화(XXE 방지)하십시오.',
    confidence: 'firm' },
  { id: 'S102', title: 'Spring @CrossOrigin 와일드카드', severity: 'medium',
    cwe: 'CWE-942', owasp: 'A05:2021',
    pattern: /@CrossOrigin\s*\(\s*(?:origins\s*=\s*)?["']\*["']/,
    remediation: '허용 출처를 구체적으로 지정하십시오.', lang: ['java'],
    confidence: 'firm' },
];

const LANG_EXT: Record<string, string> = {
  js: 'js', ts: 'ts', py: 'py', php: 'php', java: 'java', rb: 'rubygems',
  go: 'go', cs: 'csharp', cpp: 'cpp', c: 'c', rs: 'rust',
};

function detectLang(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() ?? '';
  return LANG_EXT[ext] ?? ext;
}

/** 소스 파일에서 SAST 룰 매칭하여 발견사항 생성. */
export function runSast(filename: string, content: string): Finding[] {
  const lang = detectLang(filename);
  const out: Finding[] = [];
  const lines = content.split('\n');

  for (const rule of SAST_RULES) {
    if (rule.lang && !rule.lang.includes(lang)) continue;
    const hits: { line: number; text: string }[] = [];
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i] ?? '';
      if (line.trim().startsWith('//') || line.trim().startsWith('#') || line.trim().startsWith('*')) continue;
      if (rule.pattern.test(line)) hits.push({ line: i + 1, text: line.trim().slice(0, 80) });
      if (hits.length >= 5) break;
    }
    if (hits.length) {
      out.push({
        id: id('fnd'), module: 'cve', severity: rule.severity,
        title: `[SAST ${rule.id}] ${rule.title}`,
        target: `${filename}:${hits.map(h => h.line).join(',')}`,
        description: `정적 분석으로 ${filename} 에서 취약 패턴(${rule.id})을 탐지했습니다.`,
        evidence: hits.map(h => `L${h.line}: ${h.text}`).join('\n'),
        remediation: rule.remediation,
        cwe: rule.cwe, owasp: rule.owasp,
        confidence: rule.confidence ?? 'firm',
        ...(rule.references ? { references: rule.references } : {}),
      });
    }
  }
  return out;
}
